Document: clkb
Title: Debian clkb Manual
Author: <insert document author here>
Abstract: This manual describes what clkb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/clkb/clkb.sgml.gz

Format: postscript
Files: /usr/share/doc/clkb/clkb.ps.gz

Format: text
Files: /usr/share/doc/clkb/clkb.text.gz

Format: HTML
Index: /usr/share/doc/clkb/html/index.html
Files: /usr/share/doc/clkb/html/*.html
